[workspace]
members = [
	"amf0",
	"rtmp",
	"benchmarks/video-relay",
	"tools/handshake-tester",
	"tools/rtmp-log-reader",
	"examples/mio_rtmp_server",
	"examples/threaded_rtmp_server",
	"examples/tokio_rtmp_server"
]
